"""Add AI answer and context window settings

Revision ID: d1f4fac42d78
Revises: 0002
Create Date: 2025-12-08 00:47:08.644953+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1f4fac42d78'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('collections_name_key'), 'collections', type_='unique')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=True)
    op.add_column('settings', sa.Column('default_generate_answer', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('settings', sa.Column('context_window_size', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'context_window_size')
    op.drop_column('settings', 'default_generate_answer')
    op.drop_index(op.f('ix_collections_name'), table_name='collections')
    op.create_index(op.f('ix_collections_name'), 'collections', ['name'], unique=False)
    op.create_unique_constraint(op.f('collections_name_key'), 'collections', ['name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
